import json
import ssl
import websocket

class Command():
    """
    This class sends a command to the Heatmiser Neo
    
    """

    def __init__(self, NEOHUB_URL, TOKEN):
        """
        Creates the Command object

        Args:
            NEOHUB_URL (string): The websocket url connection for the Neohub
            TOKEN (string): The API token, generated by the Heatmiser Neo app
        """

        self.NEOHUB_URL = NEOHUB_URL
        self.TOKEN = TOKEN

    def runRecipe(self, recipe_name):
        """
        This method runs a recipe on the Heatmiser Neohub

        Args:
            recipe_name (string): The name of the recipe from the Heatmiser Neo app
        """
        try:
            # Connect to NeoHub
            ws = websocket.create_connection(self.NEOHUB_URL, sslopt = {"cert_reqs": ssl.CERT_NONE})

            # Construct the message in the correct format
            command_payload = {
                "message_type": "hm_get_command_queue",
                "message": json.dumps({
                    "token": self.TOKEN,
                    "COMMANDS": [
                        {"COMMAND": f"{{'RUN_RECIPE':['{recipe_name}']}}", "COMMANDID": 1}
                    ]
                })
            }

            # Convert to JSON and send over WebSocket
            ws.send(json.dumps(command_payload))

            # Receive response
            response = ws.recv()
            print("Response from NeoHub:", response)

            # Close WebSocket connection
            ws.close()

        except Exception as e:
            print("Error:", e)